In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/imdb-top-1000-movies/data.csv

In [80]:
df = pd.read_csv('/kaggle/input/imdb-top-1000-movies/data.csv')

In [81]:
df.head()

,id,title,genres,averageRating,numVotes,releaseYear
0,tt0111161,The Shawshank Redemption,"[""Drama""]",9.3,2951083,1994
1,tt0068646,The Godfather,"[""Crime"", ""Drama""]",9.2,2057179,1972
2,tt0252487,The Chaos Class,"[""Comedy""]",9.2,43570,1975
3,tt0259534,Ramayana: The Legend of Prince Rama,"[""Action"", ""Adventure"", ""Animation""]",9.2,15407,1993
4,tt16747572,The Silence of Swastika,"[""Documentary"", ""History""]",9.2,10567,2021

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   object
 1   title          1000 non-null   object
 2   genres         1000 non-null   object
 3   averageRating  1000 non-null   float64
 4   numVotes       1000 non-null   int64
 5   releaseYear    1000 non-null   int64
dtypes: float64(1), int64(2), object(3)
memory usage: 47.0+ KB

In [83]:
df.describe()

       averageRating      numVotes  releaseYear
count    1000.000000  1.000000e+03  1000.000000
mean        8.136900  2.760164e+05  1992.287000
std         0.253836  4.273012e+05    25.646762
min         7.800000  1.012200e+04  1920.000000
25%         8.000000  2.206850e+04  1974.750000
50%         8.100000  6.615900e+04  2001.000000
75%         8.200000  3.804155e+05  2014.000000
max         9.300000  2.951083e+06  2024.000000

In [84]:
df['genres']

0                                 ["Drama"]
1                        ["Crime", "Drama"]
2                                ["Comedy"]
3      ["Action", "Adventure", "Animation"]
4                ["Documentary", "History"]
                       ...
995    ["Action", "Adventure", "Animation"]
996        ["Adventure", "Comedy", "Drama"]
997                    ["Drama", "Romance"]
998        ["Action", "Adventure", "Drama"]
999          ["Crime", "Drama", "Thriller"]
Name: genres, Length: 1000, dtype: object

In [85]:
bckup = df

In [86]:
bckup.head()

,id,title,genres,averageRating,numVotes,releaseYear
0,tt0111161,The Shawshank Redemption,"[""Drama""]",9.3,2951083,1994
1,tt0068646,The Godfather,"[""Crime"", ""Drama""]",9.2,2057179,1972
2,tt0252487,The Chaos Class,"[""Comedy""]",9.2,43570,1975
3,tt0259534,Ramayana: The Legend of Prince Rama,"[""Action"", ""Adventure"", ""Animation""]",9.2,15407,1993
4,tt16747572,The Silence of Swastika,"[""Documentary"", ""History""]",9.2,10567,2021

In [87]:
# Converting the genres to vectors


# from sklearn.feature_extraction.text import CountVectorizer
# CELL:
# cv = CountVectorizer()

In [88]:
#EDA covert list to str
import ast
df['genres_main'] = df['genres'].apply(lambda x: ast.literal_eval(x) if type(x) == str else x)

In [89]:
df['genres_main'] = df['genres_main'].apply(lambda x: ', '.join(x))

In [90]:
df.head()

,id,title,genres,averageRating,numVotes,releaseYear,genres_main
0,tt0111161,The Shawshank Redemption,"[""Drama""]",9.3,2951083,1994,Drama
1,tt0068646,The Godfather,"[""Crime"", ""Drama""]",9.2,2057179,1972,"Crime, Drama"
2,tt0252487,The Chaos Class,"[""Comedy""]",9.2,43570,1975,Comedy
3,tt0259534,Ramayana: The Legend of Prince Rama,"[""Action"", ""Adventure"", ""Animation""]",9.2,15407,1993,"Action, Adventure, Animation"
4,tt16747572,The Silence of Swastika,"[""Documentary"", ""History""]",9.2,10567,2021,"Documentary, History"

In [91]:
df.drop(['genres', 'releaseYear', 'numVotes'], axis=1, inplace=True)

In [92]:
df.head()

,id,title,averageRating,genres_main
0,tt0111161,The Shawshank Redemption,9.3,Drama
1,tt0068646,The Godfather,9.2,"Crime, Drama"
2,tt0252487,The Chaos Class,9.2,Comedy
3,tt0259534,Ramayana: The Legend of Prince Rama,9.2,"Action, Adventure, Animation"
4,tt16747572,The Silence of Swastika,9.2,"Documentary, History"

In [93]:
df[df['title'].duplicated()]

,id,title,averageRating,genres_main
301,tt4430212,Drishyam,8.2,"Crime, Drama, Mystery"
315,tt15501640,Drishyam 2,8.2,"Crime, Drama, Mystery"
473,tt0074896,The Message,8.1,"Biography, Drama, History"
518,tt2659414,Miracle in Cell No. 7,8.1,"Comedy, Drama"
885,tt0038348,Beauty and the Beast,7.9,"Drama, Fantasy, Romance"

In [94]:
df[df.duplicated('title')]

,id,title,averageRating,genres_main
301,tt4430212,Drishyam,8.2,"Crime, Drama, Mystery"
315,tt15501640,Drishyam 2,8.2,"Crime, Drama, Mystery"
473,tt0074896,The Message,8.1,"Biography, Drama, History"
518,tt2659414,Miracle in Cell No. 7,8.1,"Comedy, Drama"
885,tt0038348,Beauty and the Beast,7.9,"Drama, Fantasy, Romance"

In [95]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

cv = CountVectorizer(max_features=500, stop_words='english')

In [96]:
vector = cv.fit_transform(df['genres_main']).toarray()

In [97]:
vector.shape

(1000, 25)

In [98]:
similarity = cosine_similarity(vector)

In [99]:
similarity

array([[1.        , 0.70710678, 0.        , ..., 0.70710678, 0.57735027,
        0.57735027],
       [0.70710678, 1.        , 0.        , ..., 0.5       , 0.40824829,
        0.81649658],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.70710678, 0.5       , 0.        , ..., 1.        , 0.40824829,
        0.40824829],
       [0.57735027, 0.40824829, 0.        , ..., 0.40824829, 1.        ,
        0.33333333],
       [0.57735027, 0.81649658, 0.        , ..., 0.40824829, 0.33333333,
        1.        ]])

In [100]:
df[df['title'] == 'The Godfather'].index[0]

1

In [125]:
def recommend(movie):
    lis = []
    index = df[df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[:6]:
#         print(df.iloc[i[0]].title)
        if df.iloc[i[0]].title != movie:
            lis.append(df.iloc[i[0]].title)
    return lis

### Using both Score and Genre

In [129]:
def recommend_Wscore(movie_name):
    lis = []
    movie = df[df['title'] == movie_name]
    index = movie.index[0]
    score = movie['averageRating'].values[0]
    
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances:
        if df.iloc[i[0]].averageRating >= score:
#             print(df.iloc[i[0]].title)
            if df.iloc[i[0]].title != movie_name:
                lis.append(df.iloc[i[0]].title)
    return lis[:6]

In [130]:
recommend('The Godfather')

['The Godfather Part II',
 '12 Angry Men',
 'Pulp Fiction',
 'Nayakan',
 'City of God']

In [131]:
recommend_Wscore('The Godfather')

['The Shawshank Redemption',
 'The Chaos Class',
 'Ramayana: The Legend of Prince Rama',
 'The Silence of Swastika']

In [132]:
recommend('Terminator 2: Judgment Day')

['Inception', 'Avengers: Infinity War', 'Aliens', 'Jurassic Park', 'Maanaadu']

In [133]:
recommend_Wscore('Terminator 2: Judgment Day')

['Inception',
 'The Matrix',
 'Interstellar',
 'Ramayana: The Legend of Prince Rama',
 'The Lord of the Rings: The Return of the King',
 'The Lord of the Rings: The Fellowship of the Ring']

In [134]:
recommend('Rocketry: The Nambi Effect')

['12th Fail', 'Mahanati', 'The Elephant Man', 'Shahid', 'The Miracle Worker']

In [135]:
recommend_Wscore('Rocketry: The Nambi Effect')

['12th Fail',
 "Schindler's List",
 'Goodfellas',
 'Toma',
 'The Shawshank Redemption',
 'Fight Club']

In [136]:
recommend('Drishyam')

['The Silence of the Lambs',
 'The Departed',
 'The Hole',
 'Joker',
 'Drishyam 2',
 'Visaaranai']

In [137]:
recommend_Wscore('Drishyam')

['The Silence of the Lambs',
 'The Departed',
 'The Hole',
 'Joker',
 'Drishyam 2',
 'Visaaranai']